services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    container_name: chat-node-app
    user: ${UID}:${GID}
    volumes:
      - $APP_VOLUMES_SRC:/app/
    ports:
      - $NODE_SERVER_PORT:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
    command: npm run dev
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - $MONGO_DB_PORT:27017
    volumes:
      - ./vols/mongo-data/:/data/db
